# Alacritty Configuration File
# https://alacritty.org/config-alacritty.html
import = [
  "~/.config/alacritty/themes/themes/tomorrow_night_bright.toml"
]

[window]
opacity = 0.85

[font]
# Fonts From:
# https://www.nerdfonts.com/font-downloads
normal = { family = "HackNerdFontPropo", style = "Regular" }
bold = { family = "HackNerdFontPropo", style = "Bold" }
italic = { family = "HackNerdFontPropo", style = "Italic" }
bold_italic = { family = "HackNerdFontPropo", style = "BoldItalic" }
size = 8.25

[cursor]
style = { shape = "Block", blinking = "On" }
