# Alacritty Configuration File
# https://alacritty.org/config-alacritty.html

[window]
opacity = 0.7

[font]
# Fonts From:
# https://www.nerdfonts.com/font-downloads
normal = { family = "HackNerdFontPropo", style = "Regular" }
bold = { family = "HackNerdFontPropo", style = "Bold" }
italic = { family = "HackNerdFontPropo", style = "Italic" }
bold_italic = { family = "HackNerdFontPropo", style = "BoldItalic"} 
size = 11.25

[cursor]
style = { shape = "Block", blinking = "On" }
